import Footer from './components/Footer/Footer';
import Header from './components/Header/Header';
import './globals.css';
import { Roboto } from 'next/font/google';

const roboto = Roboto({ weight: ['400', '500', '700'], subsets: ['latin'] });

export const metadata = {
  title: 'CoinSynch',
  description: 'CoinSynch',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={roboto.className}>
        <div
          style={{ display: 'flex', flexDirection: 'column', height: '100%' }}
        >
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
